### ISSUE TITLE
Add "Citing SlicerFractionalMyocardialMass" section

### ISSUE THREAD

**Issue by jcfr** [dmolony3/SlicerFractionalMyocardialMass#2]
* [ ] Consider adding a dedicated section. 
* [x] <s>Consider adding a `CITATION.cff` file</s>

Example of `Citing` section:
* https://github.com/SCIInstitute/Cleaver#citing-cleaver
* https://docs.vtk.org/en/latest/about.html#citing
* https://slicer.readthedocs.io/en/latest/user_guide/about.html#how-to-cite
* https://autoscoper.readthedocs.io/en/latest/about.html#how-to-cite

Example of `CITATION.cff` (https://citation-file-format.github.io/)
* https://github.com/Slicer/Slicer/blob/main/CITATION.cff

**Comment by jcfr** [comment]
Since there are two publications referencing methods implemented in this module, I don't think adding a `CITATION.cff` applies here.

**Comment by dmolony3** [comment]
Thank you, I added a citing section
