### ISSUE TITLE
Register a sample dataset

### ISSUE THREAD

**Issue by jcfr** [dmolony3/SlicerFractionalMyocardialMass#4]
To help prospective user understand how to use the extension, a sampledata set should be registered and offered for download to the user.

For example, see https://github.com/Slicer/Slicer/blob/5.2/Utilities/Templates/Modules/Scripted/TemplateKey.py#L45-L89

**Comment by dmolony3** [comment]
Thanks @jcfr. I can provide sample data but I'm a little unclear on the process. Should the url link to data held on my github or is there a preferred alternative location for Slicer?

**Comment by jcfr** [comment]
> Should the url link to data held on my github or is there a preferred alternative location for Slicer?

Anticipating that your project will likely grow, I suggest to create a release called `SampleData`. This will avoid directly adding binary files to the commit history.

To create the SampleData release, consider using https://gist.github.com/jcfr/9c0c0133c2d3fa2b029e6dd2648f7720 where you would set the variables like this:

```bash
tag_name=sampledata
release_name=SampleData

org=dmolony3
proj=SlicerFractionalMyocardialMass
```

Notes:

* Consider executing the bash commands by copying into the terminal instead of running the script as a whole.
* The `hub` tool references in the script is https://hub.github.com/

Examples:
* https://github.com/BrownBiomechanics/Autoscoper/releases/tag/sample-data

**Comment by dmolony3** [comment]
Thanks, I have added sampledata and a test using the sample data.
